# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 12:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Nome da Empresa')),
                ('image', models.ImageField(upload_to='anuncios/images', verbose_name='Imagem da Empresa')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Anúncio de Empresa',
                'verbose_name_plural': 'Anúncios de Empresas',
                'ordering': ['-title'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_capa',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images', verbose_name='Imagem da Capa'),
        ),
    ]
