# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 13:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170518_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Resumo')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('image_capa', models.ImageField(blank=True, null=True, upload_to='about/images', verbose_name='Imagem da Capa')),
            ],
            options={
                'verbose_name': 'Sobre Neuly',
                'verbose_name_plural': 'Sobre Neuly',
                'ordering': ['-summary'],
            },
        ),
    ]
